### ISSUE TITLE
How to deploy to non-default VPC?

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry-community/bosh-init-bosh#3]
I'm trying to deploy to a non-default VPC and I get the following error:

```
Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Creating VM:
        Creating vm with stemcell cid 'ami-94c187fc light':
          External CPI command for method 'create_vm' returned an error: CmdError{"type":"Unknown","message":"The security group 'sg-1781d773' does not exist in default VPC 'vpc-00e19e65'","ok_to_retry":false}
```

I then tried adding the subnet as per the [bosh docs](https://bosh.io/docs/aws-cpi.html):

```
networks:
- name: default
  type: dynamic
  cloud_properties:
    subnet: subnet-1781d773
```

and got a different error:

```
Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Creating VM:
        Creating vm with stemcell cid 'ami-94c187fc light':
          External CPI command for method 'create_vm' returned an error: CmdError{"type":"Unknown","message":"When specifying a security group you must specify a group id for each item","ok_to_retry":false}
```

I appreciate this is probably a question for the bosh-aws-cpi rather than anything specific with this repo. But it might be something to add to the documentation for the various tutorials?

**Comment by robdimsdale** [comment]
This was a combination of two things:
1. Adding the `cloud_properties` to the networks fixed the first error
2. The second error was a misuse of the security group - I used the sg-id instead of the name.

**Comment by drnic** [comment]
I think I need to stop using EC2 for demos - more and more ppl have accounts without it.

**Comment by robdimsdale** [comment]
You mean EC2 vs VPC? My accounts are VPC-only.

It might be related, but I had to make some changes to the bosh micro yaml in order for it to deploy successfully:
- manually configure networking:

```
- name: default
  type: manual
  ip: 10.0.0.6
  netmask: 255.255.255.0
  gateway: 10.0.0.1
  dns: [10.0.0.6]
  cloud_properties:
    subnet: subnet-7e5b8155
```
- replace all instances of `127.0.0.1` with `10.0.0.6`

after doing that, bosh micro deploys fine with `./bin/deploy`
